const SERVER = "https://rest.unicorn.meme";

export const CONTRACTS = {
  factory: "unicorn1yvgh8xeju5dyr0zxlkvq09htvhjj20fncp5g58np4u25g8rkpgjslkfelc",
  lp: "unicorn1rn9f6ack3u8t3ed04pfaqpmh5zfp2m2ll4mkty",
  swap: "unicorn16jzpxp0e8550c9aht6q9svcux30vtyyyyxv5w2l2djjra46580wsl825uf"
};
export const ENDPOINTS = {
  supply: `${SERVER}/cosmos/bank/v1beta1/supply?pagination.limit=100`,
  factory: `${SERVER}/cosmwasm/wasm/v1/contract/${CONTRACTS.factory}/smart`,
  balances: `${SERVER}/cosmos/bank/v1beta1/balances`,
};
export const MEMOJI = [
  { ualien: "👽", listed: true },
  { ubear: "🐻", listed: true },
  { ubearhearth: "🐻❤️", listed: true },
  { ublackflag: "🏴", listed: false },
  { ublissful: "(｡◕‿‿◕｡)", listed: true },
  { ublowfish: "🐡", listed: false },
  { ucash: "💸", listed: false },
  { ucat: "🐱", listed: false },
  { uchains: "🙍⛓️", listed: true },
  { uchick: "🐤", listed: false },
  { uchina: "🇨🇳", listed: true },
  { uclown: "🤡", listed: false },
  { ucorn: "🌽", listed: true },
  { ucrystalball: "🔮", listed: false },
  { udiamond: "💎", listed: false },
  { udice: "🎲", listed: true },
  { udog: "🐶", listed: false },
  { ueggplant: "🍆", listed: true },
  { ueightball: "🎱", listed: false },
  { uenvelop: "✉️", listed: false },
  { ufahrenheit: "🔥", listed: true },
  { ufrog: "🐸", listed: true },
  { ugun: "🔫♡", listed: true },
  { umeat: "🥩", listed: true },
  { umoon: "🌕", listed: false },
  { umog: "😹", listed: true },
  { uorwell: "🐷", listed: false },
  { upaper: "📄", listed: false },
  { upeace: "☮️", listed: true },
  { upeach: "🍑", listed: true },
  { upi: "🥧", listed: true },
  { uplaceholder: "placeholder", listed: true },
  { upoo: "💩", listed: true },
  { upretzel: "🥨", listed: true },
  { uretard: "🫵🤡", listed: true },
  { urock: "🪨", listed: false },
  { urocket: "🚀", listed: true },
  { usa: "🇺🇸", listed: true },
  { uscisors: "✂️", listed: false },
  { ushot: "💉🧬", listed: true },
  { ushrimp: "🦐", listed: false },
  { uskull: "💀", listed: true },
  { usushi: "🍣", listed: true },
  { utaco: "🌮", listed: true },
  { utaiwan: "🇹🇼", listed: true },
  { utest: "test", listed: true },
  { uwatermelon: "🍉", listed: true },
  { uwunicorn: "🦄", listed: true },
];
